base_url = "https://sllvn.me"
title = "sllvn//"
author = "Andrew Sullivan"

compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "monokai", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]

[extra]
author = "Andrew Sullivan"
email = "hello@sllvn.me"
